set_property SRC_FILE_INFO {cfile:{C:/Users/Usuario/Documents/II Cuatrimestre 2021/Dispositivos_Logica_Programable/Tareas/Xilinx_projects/And/And.srcs/constrs_1/new/AND_Pines.xdc} rfile:../../../And.srcs/constrs_1/new/AND_Pines.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports B]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports A]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports Y]
