set_property SRC_FILE_INFO {cfile:{C:/Users/Usuario/Documents/II Cuatrimestre 2021/Dispositivos_Logica_Programable/Tareas/Xilinx_projects/or/or.srcs/constrs_1/new/ORpines.xdc} rfile:../../../or.srcs/constrs_1/new/ORpines.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports C]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports D]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports X]
